export const seedApplications = [
  {
    id: "syn-001",
    name: "Aisha Rao",
    role: "Frontend developer",
    city: "Bhopal",
    experience: "Beginner",
    motivation:
      "I have built small JavaScript projects, but I want to learn how a team turns a rough feature idea into requirements, architecture, tests, and a demo that another person can review.",
    availableHours: 8,
    proofUrl: "https://example.com/aisha-demo",
    buildCommitment: true,
    manualDecision: "",
  },
  {
    id: "syn-002",
    name: "Kabir Mehta",
    role: "Community manager",
    city: "Indore",
    experience: "Intermediate",
    motivation:
      "I run volunteer onboarding and want a clearer way to route people into roles without losing the reasoning behind each decision.",
    availableHours: 5,
    proofUrl: "",
    buildCommitment: true,
    manualDecision: "",
  },
  {
    id: "syn-003",
    name: "Meera Iyer",
    role: "Product designer",
    city: "Vidisha",
    experience: "Intermediate",
    motivation:
      "I want to design an accessible review flow and test whether clear reason statements help organizers challenge an automated recommendation instead of accepting it blindly.",
    availableHours: 6,
    proofUrl: "https://example.com/meera-portfolio",
    buildCommitment: true,
    manualDecision: "",
  },
  {
    id: "syn-004",
    name: "Rohan Sen",
    role: "Student",
    city: "Jabalpur",
    experience: "Beginner",
    motivation: "I want to explore AI coding and meet builders.",
    availableHours: 1,
    proofUrl: "",
    buildCommitment: false,
    manualDecision: "",
  },
  {
    id: "syn-005",
    name: "Naina Kapoor",
    role: "Backend engineer",
    city: "Bhopal",
    experience: "Advanced",
    motivation:
      "I want to prototype an audit-friendly evidence export for community programs, with deterministic rules, edge-case tests, and a clear boundary between machine recommendations and organizer decisions.",
    availableHours: 7,
    proofUrl: "https://example.com/naina-repo",
    buildCommitment: true,
    manualDecision: "Review",
  },
  {
    id: "syn-006",
    name: "Dev Malhotra",
    role: "Founder",
    city: "Indore",
    experience: "Intermediate",
    motivation:
      "Our early-stage team runs small developer sessions and needs a repeatable intake workflow that volunteers can operate without interpreting a complicated spreadsheet.",
    availableHours: 4,
    proofUrl: "https://example.com/dev-project",
    buildCommitment: true,
    manualDecision: "",
  },
];

